# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stuart Morris
tagline:          'A Homepage'
description:      "Vancouver, BC based web developer. Want to hire me? Check out my work below."
url:              http://thestu.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TheStu/thestu.github.io
