# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stuart Morris
tagline:          'A Homepage'
description:      "I'm based in Vancouver, BC, and I build cool things on the web. Sometimes for myself and sometimes for other people. If you're intereste in hiring me, you can find examples of my work below."
url:              http://thestu.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TheStu/thestu.github.io
